# Generated by Django 4.1.7 on 2023-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_alter_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
